name: Android CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Unit tests
      run: ./gradlew test
    - name: Instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        script: ./gradlew connectedAndroidTest
    - name: Lint
      run: ./gradlew lint
    - name: Coverage
      run: ./gradlew jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
